//! Axum HTTP server — serves frontend assets and API routes.
//!
//! Started in a `tokio::spawn` during Tauri setup. Supports graceful shutdown
//! via a watch channel. On `ExitRequested`, the server stops accepting new
//! connections and drains existing ones within a 5-second grace period.
//!
//! AD-9: Server lifecycle bound to Tauri's on_event(ExitRequested).
//! AD-10: Axum 0.8, no WebSocket in V1.

use std::time::Duration;

use axum::Router;
use tokio::sync::watch;
use tower_http::{
	compression::CompressionLayer,
	cors::CorsLayer,
	services::{ServeDir, ServeFile},
};
use tracing::{info, warn};

/// Start the Axum HTTP server on the given port.
///
/// Tries `port` first, then scans `port+1 .. port+5` if the initial port is busy.
/// Sends a signal on `ready_tx` once the server is successfully bound and listening.
/// The server stops cleanly when `shutdown_rx` receives a `true` value.
pub async fn start_server(
	port: u16,
	shutdown_rx: watch::Receiver<bool>,
	ready_tx: std::sync::mpsc::Sender<()>,
) {
	// Resolve the dist path for static file serving.
	let dist_path = resolve_dist_path();

	// 1. Build the API router — mounted at /api/*.
	let api_router = crate::api::router();

	// 2. Static file serving with SPA fallback.
	//    If dist/ does not exist, skip static serving entirely (dev mode).
	let app = if std::path::Path::new(&dist_path).exists() {
		let index_path = format!("{}/index.html", dist_path);
		let fs_serve = ServeDir::new(&dist_path)
			.append_index_html_on_directories(true)
			.fallback(ServeFile::new(index_path));

		Router::new()
			.nest("/api", api_router)
			.fallback_service(fs_serve)
			.layer(CompressionLayer::new())
			.layer(CorsLayer::permissive())
	} else {
		info!("dist/ directory not found — serving API only (expected in dev mode)");
		Router::new()
			.nest("/api", api_router)
			.layer(CompressionLayer::new())
			.layer(CorsLayer::permissive())
	};

	// 3. Bind to the port (or scan a range).
	let listener = match bind_with_fallback(port).await {
		Some(l) => l,
		None => {
			warn!("Could not bind to any port in range {}-{} — server not started", port, port + 5);
			return;
		}
	};
	let actual_port = listener.local_addr().unwrap().port();

	// Signal that the server is ready (fixes race condition with window opening).
	let _ = ready_tx.send(());

	info!("Axum server listening on http://0.0.0.0:{}", actual_port);

	// 4. Run with graceful shutdown.
	let serve_future = axum::serve(listener, app).with_graceful_shutdown(async move {
		let mut rx = shutdown_rx;
		loop {
			rx.changed().await.ok();
			if *rx.borrow() {
				info!("Graceful shutdown initiated — draining in-flight requests");
				break;
			}
		}
	});

	match tokio::time::timeout(Duration::from_secs(5), serve_future).await {
		Ok(Ok(())) => info!("Axum server stopped cleanly"),
		Ok(Err(e)) => warn!("Axum server exited with error: {}", e),
		Err(_) => warn!("Axum server shutdown timed out after 5s — forcing stop"),
	}
}

/// Try to bind on `base_port`, then scan up to `base_port + 5`.
async fn bind_with_fallback(base_port: u16) -> Option<tokio::net::TcpListener> {
	for port in base_port..=base_port.saturating_add(5) {
		let addr = format!("0.0.0.0:{}", port);
		match tokio::net::TcpListener::bind(&addr).await {
			Ok(l) => return Some(l),
			Err(_) if port < base_port + 5 => {
				warn!("Port {} in use, trying next...", port);
				continue;
			}
			Err(e) => {
				warn!("Failed to bind on {}: {}", addr, e);
				continue;
			}
		}
	}
	None
}

/// Resolve the path to the frontend `dist/` directory.
///
/// Priority:
/// 1. `../dist/` relative to CWD (dev: generated by `nuxt generate`)
/// 2. `dist/` in CWD (execution fallback)
///
/// In prod Tauri builds, the resource path is determined by Tauri and should
/// be passed explicitly via `app.path().resource_dir()` (future enhancement).
fn resolve_dist_path() -> String {
	if std::path::Path::new("../dist").exists() {
		return "../dist".to_string();
	}
	if std::path::Path::new("dist").exists() {
		return "dist".to_string();
	}
	// Return the path anyway — caller will check existence.
	"dist".to_string()
}
